### ISSUE TITLE
Site cannot be reached

### ISSUE THREAD

**Issue by saswat0** [cihat/full-stack-twitter-clone#20]
I tried starting the app via docker by issuing `docker-compose up` but the site isn't reachable

Here are the logs printed out while the containers were getting spawned
```
Creating fullstacktwitterclone_frontend_1 ... done
Creating fullstacktwitterclone_backend_1  ... done
Creating fullstacktwitterclone_mongodb_1  ... done
Attaching to fullstacktwitterclone_backend_1, fullstacktwitterclone_mongodb_1, fullstacktwitterclone_frontend_1
backend_1   |
backend_1   | > full-stack-twitter-clone@1.0.0 start /app
backend_1   | > node src/.bin/www
backend_1   |
backend_1   | Mon, 11 Jul 2022 11:39:55 GMT express-session deprecated undefined resave option; provide resave option at src/app.js:60:3
backend_1   | Mon, 11 Jul 2022 11:39:55 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at src/app.js:60:3
backend_1   | Mon, 11 Jul 2022 11:39:55 GMT express-session deprecated req.secret; provide secret option at src/app.js:60:3
mongodb_1   | 2022-07-11T11:39:55.572+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongodb_1   | 2022-07-11T11:39:55.575+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=62c9c1beae00
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten] db version v4.2.21
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten] git version: b0aeed9445ff41af07449fa757e1f231bce990b3
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten] modules: none
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten] build environment:
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten]     distarch: x86_64
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
mongodb_1   | 2022-07-11T11:39:55.575+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
mongodb_1   | 2022-07-11T11:39:55.576+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongodb_1   | 2022-07-11T11:39:55.576+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3479M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
backend_1   | MongoParseError: Invalid connection string
backend_1   |     at parseConnectionString (/app/node_modules/mongodb/lib/core/uri_parser.js:585:21)
backend_1   |     at connect (/app/node_modules/mongodb/lib/operations/connect.js:283:3)
backend_1   |     at /app/node_modules/mongodb/lib/mongo_client.js:284:5
backend_1   |     at maybePromise (/app/node_modules/mongodb/lib/utils.js:692:3)
backend_1   |     at MongoClient.connect (/app/node_modules/mongodb/lib/mongo_client.js:280:10)
backend_1   |     at /app/node_modules/mongoose/lib/connection.js:836:12
backend_1   |     at new Promise (<anonymous>)
backend_1   |     at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:832:19)
backend_1   |     at /app/node_modules/mongoose/lib/index.js:351:10
backend_1   |     at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
backend_1   |     at new Promise (<anonymous>)
backend_1   |     at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
backend_1   |     at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1149:10)
backend_1   |     at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:350:20)
backend_1   |     at Object.<anonymous> (/app/src/mongo-connection.js:14:4)
backend_1   |     at Module._compile (internal/modules/cjs/loader.js:1200:30)
frontend_1  | yarn run v1.22.4
frontend_1  | error Command "serve" not found.
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
mongodb_1   | 2022-07-11T11:39:56.210+0000 I  STORAGE  [initandlisten] WiredTiger message [1657539596:210903][1:0x7f8a1c3a8b00], txn-recover: Recovering log 5 through 6
mongodb_1   | 2022-07-11T11:39:56.233+0000 I  STORAGE  [initandlisten] WiredTiger message [1657539596:233504][1:0x7f8a1c3a8b00], txn-recover: Recovering log 6 through 6
mongodb_1   | 2022-07-11T11:39:56.270+0000 I  STORAGE  [initandlisten] WiredTiger message [1657539596:270175][1:0x7f8a1c3a8b00], txn-recover: Main recovery loop: starting at 5/4864 to 6/256
mongodb_1   | 2022-07-11T11:39:56.315+0000 I  STORAGE  [initandlisten] WiredTiger message [1657539596:315407][1:0x7f8a1c3a8b00], txn-recover: Recovering log 5 through 6
mongodb_1   | 2022-07-11T11:39:56.427+0000 I  STORAGE  [initandlisten] WiredTiger message [1657539596:427669][1:0x7f8a1c3a8b00], txn-recover: Recovering log 6 through 6
mongodb_1   | 2022-07-11T11:39:56.450+0000 I  STORAGE  [initandlisten] WiredTiger message [1657539596:450516][1:0x7f8a1c3a8b00], txn-recover: Set global recovery timestamp: (0, 0)
fullstacktwitterclone_frontend_1 exited with code 1
mongodb_1   | 2022-07-11T11:39:56.930+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongodb_1   | 2022-07-11T11:39:56.932+0000 I  STORAGE  [initandlisten] No table logging settings modifications are required for existing WiredTiger tables. Logging enabled? 1
mongodb_1   | 2022-07-11T11:39:56.933+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
mongodb_1   | 2022-07-11T11:39:57.060+0000 I  CONTROL  [initandlisten]
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten]
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten]
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten]
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongodb_1   | 2022-07-11T11:39:57.061+0000 I  CONTROL  [initandlisten]
mongodb_1   | 2022-07-11T11:39:57.064+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
mongodb_1   | 2022-07-11T11:39:57.066+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongodb_1   | 2022-07-11T11:39:57.069+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
mongodb_1   | 2022-07-11T11:39:57.069+0000 I  NETWORK  [listener] Listening on 0.0.0.0
mongodb_1   | 2022-07-11T11:39:57.069+0000 I  NETWORK  [listener] waiting for connections on port 27017
```
Any help in this regard would be really great! TIA

**Comment by WombleWoo7547** [comment]
It's broken because yarn is saying that "yarn run serve" isn't a command. Ima check it out and get back to you

**Comment by WombleWoo7547** [comment]
PR #21
